apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-foundations-service-a
  namespace: default
  labels:
    app: gitops-foundations-service-a
spec:
  revisionHistoryLimit: 0
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gitops-foundations-service-a
  template:
    metadata:
      labels:
        app: gitops-foundations-service-a
    spec:
      containers:
      - name: gitops-foundations-service-a
        image: delca/gitops-foundations-service-a:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
          failureThreshold: 4
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
