apiVersion: v1
kind: Service
metadata:
  name: gitops-foundations-service-a
  namespace: argocd-exercise-service-a
spec:
  type: NodePort
  selector:
    app: gitops-foundations-service-a
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
